// This is C2E2f_passthru from "The Cg Tutorial" (Addison-Wesley, ISBN
// 0321194969) by Randima Fernando and Mark J. Kilgard.  See page 53.'

#include "StandardConstants.fx"
#include "StandardTextureResources.fx"
#include "samplerhelper.fx"

struct C2E2f_Output {
  float4 color : COLOR;

};

C2E2f_Output main(float4 color : COLOR, float2 texCoord0 : TEXCOORD0)
{
  C2E2f_Output OUT;
  OUT.color = sample2D(gDiffuseMapSampler, texCoord0, void);// ;
  return OUT;
}
