
#include "StandardControllerEvents.h"

#include "../Lua/LuaEnvironment.h"

namespace PE {
namespace Events {

// Button down events
	PE_IMPLEMENT_CLASS1(Event_BUTTON_Y_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_B_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_A_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_X_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_L_THUMB_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_R_THUMB_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_L_SHOULDER_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_R_SHOULDER_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_BACK_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_START_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_PAD_N_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_PAD_S_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_PAD_E_DOWN, Event);
	PE_IMPLEMENT_CLASS1(Event_PAD_W_DOWN, Event);

// Button up events
	PE_IMPLEMENT_CLASS1(Event_BUTTON_Y_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_B_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_A_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_X_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_L_THUMB_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_R_THUMB_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_L_SHOULDER_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_R_SHOULDER_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_BACK_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_START_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_PAD_N_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_PAD_S_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_PAD_E_UP, Event);
	PE_IMPLEMENT_CLASS1(Event_PAD_W_UP, Event);

// Thumb & trigger move events
	PE_IMPLEMENT_CLASS1(Event_ANALOG_L_THUMB_MOVE, Event);
	PE_IMPLEMENT_CLASS1(Event_ANALOG_R_THUMB_MOVE, Event);
	PE_IMPLEMENT_CLASS1(Event_ANALOG_L_TRIGGER_MOVE, Event);
	PE_IMPLEMENT_CLASS1(Event_ANALOG_R_TRIGGER_MOVE, Event);

// Button held events
	PE_IMPLEMENT_CLASS1(Event_BUTTON_Y_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_B_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_A_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_X_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_L_THUMB_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_R_THUMB_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_L_SHOULDER_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_R_SHOULDER_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_BACK_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_BUTTON_START_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_PAD_N_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_PAD_S_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_PAD_E_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_PAD_W_HELD, Event);
	
};
};

